"""init models

Revision ID: 05407c8f883c
Revises: ac4beec51dce
Create Date: 2025-12-22 12:32:46.160616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05407c8f883c'
down_revision: Union[str, None] = 'ac4beec51dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('budgets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('period', sa.Enum('MONTHLY', name='budgetperiod'), nullable=False),
    sa.Column('start_month', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_b_user_month', 'budgets', ['user_id', 'start_month'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'IMPORT', 'API', name='entrysource'), nullable=False),
    sa.Column('status', sa.Enum('POSTED', 'VOID', name='entrystatus'), nullable=False),
    sa.Column('correction_of_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('reversal_of_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['correction_of_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['reversal_of_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_je_user_status', 'journal_entries', ['user_id', 'status'], unique=False)
    op.create_index('idx_je_user_time', 'journal_entries', ['user_id', 'occurred_at'], unique=False)
    op.create_table('ledger_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.Enum('ASSET', 'LIABILITY', 'INCOME', 'EXPENSE', 'EQUITY', name='accounttype'), nullable=False),
    sa.Column('subtype', sa.String(length=40), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['ledger_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_la_user_name')
    )
    op.create_index('idx_la_user_name', 'ledger_accounts', ['user_id', 'name'], unique=False)
    op.create_index('idx_la_user_type', 'ledger_accounts', ['user_id', 'type'], unique=False)
    op.create_table('budget_lines',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('budget_id', sa.BigInteger(), nullable=False),
    sa.Column('expense_account_id', sa.BigInteger(), nullable=False),
    sa.Column('limit_minor', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['expense_account_id'], ['ledger_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id', 'expense_account_id', name='uq_bl')
    )
    op.create_table('postings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('journal_entry_id', sa.BigInteger(), nullable=False),
    sa.Column('ledger_account_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['ledger_account_id'], ['ledger_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_p_je', 'postings', ['journal_entry_id'], unique=False)
    op.create_index('idx_p_la_time', 'postings', ['ledger_account_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_p_la_time', table_name='postings')
    op.drop_index('idx_p_je', table_name='postings')
    op.drop_table('postings')
    op.drop_table('budget_lines')
    op.drop_index('idx_la_user_type', table_name='ledger_accounts')
    op.drop_index('idx_la_user_name', table_name='ledger_accounts')
    op.drop_table('ledger_accounts')
    op.drop_index('idx_je_user_time', table_name='journal_entries')
    op.drop_index('idx_je_user_status', table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index('idx_b_user_month', table_name='budgets')
    op.drop_table('budgets')
    op.drop_table('users')
    # ### end Alembic commands ###
